// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiIHbdakKCuRnTbh5AD2iKlXkX8Nfa8Lk',
    appId: '1:812634494757:web:4e6fa4bf6f3f6b1e9faccc',
    messagingSenderId: '812634494757',
    projectId: 'skillshodh',
    authDomain: 'skillshodh.firebaseapp.com',
    storageBucket: 'skillshodh.appspot.com',
    measurementId: 'G-V2K4SD5P92',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4S4yr-RAjE0udFTAwjT3cHKW4nwmclz4',
    appId: '1:812634494757:android:c046d809bd86acaf9faccc',
    messagingSenderId: '812634494757',
    projectId: 'skillshodh',
    storageBucket: 'skillshodh.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSFl-tJ5Jnxn8gqaO_9z1C-OVqiAJQb50',
    appId: '1:812634494757:ios:fab7a68cbdd28f9e9faccc',
    messagingSenderId: '812634494757',
    projectId: 'skillshodh',
    storageBucket: 'skillshodh.appspot.com',
    iosBundleId: 'startapp.solutions.skillshodh',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSFl-tJ5Jnxn8gqaO_9z1C-OVqiAJQb50',
    appId: '1:812634494757:ios:2c29feb20d37695d9faccc',
    messagingSenderId: '812634494757',
    projectId: 'skillshodh',
    storageBucket: 'skillshodh.appspot.com',
    iosBundleId: 'startapp.solutions.skillshodh.RunnerTests',
  );
}
